"""T3 dual-certificate test: can nonneg ridge measures produce the Laplacian of
a smoothed triple junction?

Question (T3, docs/theory-ladder.md): is every convex Lipschitz g in the closure
of the cone class {sum c_i ReLU(w_i.x - b_i), c_i >= 0} + affine?

Test: search for a dual certificate psi on Omega = [-S,S]^2 with
    (i)  integral of psi over ell ∩ Omega  <= 0   for every line ell,
    (ii) <Delta g, psi>  >  0.
If psi exists, Delta g is separated from the closed cone generated by
{H^1 on ell ∩ Omega : ell line}; since uniform convergence of functions implies
distributional convergence of Laplacians, the cone class cannot approximate g
uniformly on Omega AT ANY MASS — T3 is false (numerically, on the sampled line
family; margins reported).

Targets:
  A (sanity, in-cone): sum of random softplus ridges (softplus = positive
    b-average of ReLUs => in the cone closure). Expected LP optimum ~ 0.
  B (junction):  g = eta*LSE(v_i.x/eta), three unit gradients at 120 degrees.
    Crease rays END at the junction; conjecture: certificate exists, optimum > 0.

LP:  maximize  sum_cells Delta_g * h^2 * psi   s.t.  A_lines psi <= 0,  |psi| <= 1.
"""

import time

import numpy as np
from scipy import sparse
from scipy.optimize import linprog

rng = np.random.default_rng(0)
METHOD = "highs-ipm"   # interior point: handles the dense mean-zero row and the
                       # degenerate bang-bang face; dual simplex churned >1 h.

# ---------------- grid ----------------
S = 3.0          # half-side of the square Omega
n = 61           # cells per side
h = 2 * S / n
centers = -S + h * (np.arange(n) + 0.5)
X, Y = np.meshgrid(centers, centers, indexing="ij")   # (n, n)
ncell = n * n

# ---------------- targets ----------------
ETA = 0.3

def laplacian_lse(X, Y, eta=ETA):
    """Delta g for g = eta*log(sum exp(v_i.x/eta)), |v_i|=1 at 120 deg.
    Closed form: Delta g = (1/eta) * (1 - |sum p_i v_i|^2), p = softmax."""
    angs = np.deg2rad([90.0, 210.0, 330.0])
    V = np.stack([np.cos(angs), np.sin(angs)], axis=1)          # (3, 2)
    Z = np.stack([(V[i, 0] * X + V[i, 1] * Y) / eta for i in range(3)])
    Z -= Z.max(axis=0, keepdims=True)
    P = np.exp(Z); P /= P.sum(axis=0, keepdims=True)            # softmax (3,n,n)
    mx = sum(P[i] * V[i, 0] for i in range(3))
    my = sum(P[i] * V[i, 1] for i in range(3))
    return (1.0 - (mx**2 + my**2)) / eta

def laplacian_softplus_sum(X, Y, k=5, eta=ETA):
    """Delta g for g = sum_j c_j * eta*softplus((w_j.x - b_j)/eta), c_j >= 0.
    Each term: Delta = (c_j/eta) * s(1-s), s = sigmoid((w.x-b)/eta). IN-CONE."""
    out = np.zeros_like(X)
    for _ in range(k):
        th = rng.uniform(0, np.pi)
        w = np.array([np.cos(th), np.sin(th)])
        b = rng.uniform(-1.5, 1.5)
        c = rng.uniform(0.5, 2.0)
        t = (w[0] * X + w[1] * Y - b) / eta
        s = 1.0 / (1.0 + np.exp(-np.clip(t, -60, 60)))
        out += c * s * (1.0 - s) / eta
    return out

# ---------------- line family & constraint matrix ----------------
def build_line_matrix(n_theta=90, db=h):
    """Rows: sampled lines; cols: cells; entries: chord quadrature weights."""
    rows, cols, vals = [], [], []
    r = 0
    bmax = S * np.sqrt(2.0)
    ds = h / 2.0
    for j in range(n_theta):
        th = np.pi * j / n_theta
        nx, ny = np.cos(th), np.sin(th)          # line normal
        tx, ty = -ny, nx                          # tangent
        for b in np.arange(-bmax, bmax + 1e-9, db):
            # param x = b*n + t*tau ; clip to square
            # |b*nx + t*tx| <= S and |b*ny + t*ty| <= S
            tlo, thi = -1e18, 1e18
            for (pn, pt) in ((b * nx, tx), (b * ny, ty)):
                if abs(pt) < 1e-12:
                    if abs(pn) > S:
                        tlo, thi = 1.0, 0.0
                        break
                else:
                    a1, a2 = (-S - pn) / pt, (S - pn) / pt
                    tlo = max(tlo, min(a1, a2))
                    thi = min(thi, max(a1, a2))
            if thi - tlo < 3 * ds:
                continue
            ts = np.arange(tlo + ds / 2, thi, ds)
            px = b * nx + ts * tx
            py = b * ny + ts * ty
            ix = np.clip(((px + S) / h).astype(int), 0, n - 1)
            iy = np.clip(((py + S) / h).astype(int), 0, n - 1)
            cell = ix * n + iy
            w = np.bincount(cell, minlength=ncell) * ds
            nz = np.nonzero(w)[0]
            rows.extend([r] * len(nz)); cols.extend(nz.tolist())
            vals.extend(w[nz].tolist())
            r += 1
    A = sparse.csr_matrix((vals, (rows, cols)), shape=(r, ncell))
    return A

print("building line constraint matrix ...")
A = build_line_matrix()
print(f"  lines: {A.shape[0]},  nnz: {A.nnz}")

# ---------------- solve LP for a given target ----------------
def run(name, lap, mean_zero=False):
    """mean_zero=True adds the constraint  integral(psi) >= 0  (binds at 0).
    This refutes the MODEL with free quadratic head: Delta g + lambda*const
    must stay outside the cone for every lambda >= 0, which requires a
    certificate with nonnegative (hence zero) mean."""
    c_obj = (lap * h * h).ravel()
    norm = np.abs(c_obj).sum()                      # ~ ||Delta g||_L1(Omega)
    A_ub, b_ub = A, np.zeros(A.shape[0])
    if mean_zero:
        row = sparse.csr_matrix(-np.full((1, ncell), h * h))   # -int psi <= 0
        A_ub = sparse.vstack([A, row]).tocsr()
        b_ub = np.zeros(A.shape[0] + 1)
    t0 = time.time()
    res = linprog(
        -c_obj,                                    # maximize c.psi
        A_ub=A_ub, b_ub=b_ub,
        bounds=(-1.0, 1.0),
        method=METHOD,
    )
    dt = time.time() - t0
    val = -res.fun
    rel = val / norm
    print(f"[{name}] LP optimum = {val:.6f}   ||Delta g||_1 = {norm:.3f}   "
          f"relative = {rel:.2%}   [{dt:.1f}s]   status: {res.message}",
          flush=True)
    if val > 1e-6:
        psi = res.x.reshape(n, n)
        # where is the certificate positive? distance of positive cells to origin
        pos = psi > 0.5
        if pos.any():
            rr = np.sqrt(X[pos] ** 2 + Y[pos] ** 2)
            print(f"      psi>0.5 on {pos.sum()} cells,  r in "
                  f"[{rr.min():.2f}, {rr.max():.2f}]  (junction at r=0)")
        worst = (A @ res.x).max()
        print(f"      max line-integral of psi (feasibility) = {worst:.2e}")
    return val, rel

print("\n-- sanity target A: sum of softplus ridges (IN cone) --")
lapA = laplacian_softplus_sum(X, Y)
vA, rA = run("A softplus-sum", lapA)

print("\n-- main target B: smoothed triple junction (LSE) --")
lapB = laplacian_lse(X, Y)
vB, rB = run("B LSE junction", lapB)

print("\nverdict (pure cone, T3): certificate ratio B/A =",
      f"{(rB / max(rA, 1e-12)):.1f}x" if rA > 0 else f"(A ~ 0)  B rel = {rB:.2%}")

print("\n==== mean-zero certificates (refute model WITH free quadratic head) ====")
print("\n-- sanity A, mean-zero --")
vA0, rA0 = run("A softplus-sum +head", lapA, mean_zero=True)
print("\n-- junction B, mean-zero --")
vB0, rB0 = run("B LSE junction +head", lapB, mean_zero=True)
print("\nverdict (model with free C): junction rel =", f"{rB0:.2%}",
      " vs sanity rel =", f"{rA0:.2%}")
print("interpretation: large junction value => quadratic head does NOT rescue"
      " capacity; ~noise value => head buys back junctions at curvature price.")
